spring.application.name=Olympic Management System

server.port=8083

# Activation de la base H2 en mémoire (persistante durant l'exécution)
spring.datasource.url=jdbc:h2:mem:olympicdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Activation de la console Web H2 pour visualiser la BD sur votre navigateur
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuration JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuration Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
